"""Initial migration

Revision ID: 259bc6bf294b
Revises: 
Create Date: 2026-06-19 13:46:38.312007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259bc6bf294b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Aircrafts',
    sa.Column('AircraftID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AircraftCode', sa.String(length=20), nullable=True),
    sa.Column('AircraftName', sa.String(length=100), nullable=True),
    sa.Column('TotalSeats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('AircraftID')
    )
    op.create_table('Airports',
    sa.Column('AirportID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AirportCode', sa.String(length=10), nullable=True),
    sa.Column('AirportName', sa.String(length=100), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('AirportID'),
    sa.UniqueConstraint('AirportCode')
    )
    op.create_table('Passengers',
    sa.Column('PassengerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('Nationality', sa.String(length=50), nullable=True),
    sa.Column('IdentifierType', sa.String(length=20), nullable=True),
    sa.Column('IdentifierNumber', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('PassengerID')
    )
    op.create_table('Promotions',
    sa.Column('PromotionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PromoCode', sa.String(length=50), nullable=True),
    sa.Column('DiscountPercent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PromotionID')
    )
    op.create_table('SeatClasses',
    sa.Column('SeatClassID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClassName', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('SeatClassID')
    )
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Role', sa.String(length=20), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Bookings',
    sa.Column('BookingID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('BookingDate', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('BookingID')
    )
    op.create_table('Flights',
    sa.Column('FlightID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FlightNumber', sa.String(length=20), nullable=True),
    sa.Column('DepartureAirportID', sa.Integer(), nullable=True),
    sa.Column('ArrivalAirportID', sa.Integer(), nullable=True),
    sa.Column('AircraftID', sa.Integer(), nullable=True),
    sa.Column('DepartureTime', sa.DateTime(), nullable=True),
    sa.Column('ArrivalTime', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['AircraftID'], ['Aircrafts.AircraftID'], ),
    sa.ForeignKeyConstraint(['ArrivalAirportID'], ['Airports.AirportID'], ),
    sa.ForeignKeyConstraint(['DepartureAirportID'], ['Airports.AirportID'], ),
    sa.PrimaryKeyConstraint('FlightID'),
    sa.UniqueConstraint('FlightNumber')
    )
    op.create_table('PassengerBaggages',
    sa.Column('BaggageID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PassengerID', sa.Integer(), nullable=True),
    sa.Column('Weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['PassengerID'], ['Passengers.PassengerID'], ),
    sa.PrimaryKeyConstraint('BaggageID')
    )
    op.create_table('FlightSeats',
    sa.Column('FlightSeatID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FlightID', sa.Integer(), nullable=True),
    sa.Column('SeatClassID', sa.Integer(), nullable=True),
    sa.Column('SeatNumber', sa.String(length=10), nullable=True),
    sa.Column('Price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['FlightID'], ['Flights.FlightID'], ),
    sa.ForeignKeyConstraint(['SeatClassID'], ['SeatClasses.SeatClassID'], ),
    sa.PrimaryKeyConstraint('FlightSeatID')
    )
    op.create_table('Payments',
    sa.Column('PaymentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=True),
    sa.Column('PaymentDate', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['BookingID'], ['Bookings.BookingID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    op.create_table('Tickets',
    sa.Column('TicketID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=True),
    sa.Column('PassengerID', sa.Integer(), nullable=True),
    sa.Column('FlightSeatID', sa.Integer(), nullable=True),
    sa.Column('TicketNumber', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['BookingID'], ['Bookings.BookingID'], ),
    sa.ForeignKeyConstraint(['FlightSeatID'], ['FlightSeats.FlightSeatID'], ),
    sa.ForeignKeyConstraint(['PassengerID'], ['Passengers.PassengerID'], ),
    sa.PrimaryKeyConstraint('TicketID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tickets')
    op.drop_table('Payments')
    op.drop_table('FlightSeats')
    op.drop_table('PassengerBaggages')
    op.drop_table('Flights')
    op.drop_table('Bookings')
    op.drop_table('Users')
    op.drop_table('SeatClasses')
    op.drop_table('Promotions')
    op.drop_table('Passengers')
    op.drop_table('Airports')
    op.drop_table('Aircrafts')
    # ### end Alembic commands ###
